//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.DA.Users {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDAUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDAUser() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Job.DA.Users.ResourceDAUser", typeof(ResourceDAUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM Degree.
        /// </summary>
        internal static string GetDegree {
            get {
                return ResourceManager.GetString("GetDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///EmployerId
        ///,EmployerUser AS NameUser
        ///,Email
        ///,Phone
        ///,CurrentEmployee
        ///,EmployerPassword AS UserPassword
        ///,IndustryId 
        ///FROM Employer 
        ///WHERE (EmployerUser = &apos;{0}&apos; OR Email = &apos;{1}&apos;) AND EmployerPassword = &apos;{2}&apos;.
        /// </summary>
        internal static string GetEmployer {
            get {
                return ResourceManager.GetString("GetEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM Industry.
        /// </summary>
        internal static string GetIndustry {
            get {
                return ResourceManager.GetString("GetIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM Users 
        ///WHERE (NameUser = &apos;{0}&apos; OR Email = &apos;{1}&apos;) AND UserPassword = &apos;{2}&apos;.
        /// </summary>
        internal static string GetUser {
            get {
                return ResourceManager.GetString("GetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Employer
        ///(EmployerUser,Email,Phone,CurrentEmployee,EmployerPassword,IndustryId)
        ///VALUES
        ///(@NameUser, @Email, @Phone, @CurrentEmployee, @UserPassword, @IndustryId).
        /// </summary>
        internal static string SaveEmployer {
            get {
                return ResourceManager.GetString("SaveEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Users
        ///(NameUser,Email,Phone,UserPassword,DegreeId)
        ///VALUES
        ///(@NameUser, @Email, @Phone, @UserPassword, @DegreeId).
        /// </summary>
        internal static string SaveUser {
            get {
                return ResourceManager.GetString("SaveUser", resourceCulture);
            }
        }
    }
}
