//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.DA.Offer {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceDAOffer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceDAOffer() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Job.DA.Offer.ResourceDAOffer", typeof(ResourceDAOffer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT U.NameUser, U.Email, U.Phone, O.OfferDescription 
        ///FROM OfferApply OA
        ///INNER JOIN Users U ON U.UserId = OA.UserId
        ///INNER JOIN Offer O ON O.OfferId = OA.OfferId
        ///WHERE O.EmployerId = {0}.
        /// </summary>
        internal static string GetOfferApply {
            get {
                return ResourceManager.GetString("GetOfferApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT O.OfferId, O.OfferDescription, O.CurrentVacancy, O.EmployerId, E.EmployerUser AS Empresa
        ///FROM Offer O
        ///INNER JOIN Employer E ON E.EmployerId = O.EmployerId.
        /// </summary>
        internal static string GetOffers {
            get {
                return ResourceManager.GetString("GetOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Offer(OfferDescription,CurrentVacancy,EmployerId)
        ///VALUES(@OfferDescription, @CurrentVacancy, @EmployerId).
        /// </summary>
        internal static string SaveOffer {
            get {
                return ResourceManager.GetString("SaveOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO OfferApply(UserId, OfferId)
        ///VALUES(@UserId, @OfferId).
        /// </summary>
        internal static string SaveOfferApply {
            get {
                return ResourceManager.GetString("SaveOfferApply", resourceCulture);
            }
        }
    }
}
