//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Services {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Job.Services.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/User/GetDegree.
        /// </summary>
        public static string GetDegree {
            get {
                return ResourceManager.GetString("GetDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/User/GetEmployer.
        /// </summary>
        public static string GetEmployer {
            get {
                return ResourceManager.GetString("GetEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/User/GetIndustry.
        /// </summary>
        public static string GetIndustry {
            get {
                return ResourceManager.GetString("GetIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/Offer/GetOffers.
        /// </summary>
        public static string GetOffers {
            get {
                return ResourceManager.GetString("GetOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/Offer/GetOffersApply.
        /// </summary>
        public static string GetOffersApply {
            get {
                return ResourceManager.GetString("GetOffersApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/User/GetUser.
        /// </summary>
        public static string GetUser {
            get {
                return ResourceManager.GetString("GetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/User/SaveEmployer.
        /// </summary>
        public static string SaveEmployer {
            get {
                return ResourceManager.GetString("SaveEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/Offer/SaveOffer.
        /// </summary>
        public static string SaveOffer {
            get {
                return ResourceManager.GetString("SaveOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/Offer/SaveOfferApply.
        /// </summary>
        public static string SaveOfferApply {
            get {
                return ResourceManager.GetString("SaveOfferApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a gateway/User/SaveUser.
        /// </summary>
        public static string SaveUser {
            get {
                return ResourceManager.GetString("SaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost:7037/.
        /// </summary>
        public static string UrlBase {
            get {
                return ResourceManager.GetString("UrlBase", resourceCulture);
            }
        }
    }
}
